name: CitySystem
version: 0.1
main: de.malteee.citysystem.CitySystem
author: Malteee
api-version: 1.21

commands:
  spawn:
    description: teleports you to the spawn
  setSpawn:
    description: sets the spawn
  breakShop:
    description: let's you break a shop
  world:
    description: admin use only
  money:
    description: shows you your balance
  home:
    description: to set a home and teleport to it
  farmWorld:
    description: teleports you to the farmWorld
  mainWorld:
    description: teleports you to the mainWorld
  createSuperiorArea:
    description: admin use only
  hologram:
    description: admin use only
  pos1:
    description: sets position 1
  pos2:
    description: sets position 2
  msg:
    description: write a private message to someone
  city:
    description: city command
  setMainSpawn:
    description: admin use only